version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finance-rag-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=/api
    depends_on:
      - backend
    networks:
      - finance-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-rag-backend
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./data:/app/data
    networks:
      - finance-network
    restart: unless-stopped

networks:
  finance-network:
    driver: bridge

volumes:
  data:
    driver: local
