# Render Blueprint Specification
# See: https://render.com/docs/blueprint-spec

services:
  # Main Application Service with Embedded ChromaDB
  - type: web
    name: finance-rag-app
    plan: free
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader popular
      python -m spacy download en_core_web_sm
    startCommand: >-
      gunicorn --bind :$PORT 
      --workers 2 
      --threads 4 
      --timeout 120 
      --preload 
      finance_rag_app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: VECTOR_STORE_DIR
        value: "/opt/render/project/src/chroma_db"
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PORT
        value: "10000"

# Deployment Notes:
# 1. Set the following environment variables in the Render dashboard:
#    - GROQ_API_KEY: Your Groq API key
#    - GOOGLE_API_KEY: Your Google API key
# 2. The application will be available at the Render-provided URL
# 3. For production, consider using a managed vector database like Pinecone or Weaviate
