# Render Blueprint Specification
# See: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: finance-rag-backend
    plan: free
    buildCommand: "chmod +x setup.sh && ./setup.sh"
    startCommand: "gunicorn --bind :$PORT --workers 2 --threads 4 --timeout 120 finance_rag_app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: VECTOR_STORE_DIR
        value: "/opt/render/project/src/chroma_db"
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PORT
        value: "10000"

# Deployment Notes:
# 1. The setup script (setup.sh) will handle the initial setup
# 2. Environment variables marked with sync: false must be set in the Render dashboard
# 3. The vector store will persist in /opt/render/project/src/chroma_db
# 4. The application will be available at the Render-provided URL
