services:
  - type: web
    name: finance-rag-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn finance_rag_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: VECTOR_STORE_DIR
        value: "/opt/render/project/src/chroma_db"
      - key: FLASK_ENV
        value: production
